name: IT Design
favicon: null
layout_spectrum: 0.49326
typography_spectrum: 0
title: Your Home Your Imagination
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f8f9f4'
    - '#7c5c4b'
    - '#b4abbb'
    - '#3a2822'
    - '#6d8bb5'
  brandStrength: 0
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
